uint32 revision
uint32 max_num_revisions   # Maximum number of revisions to receive.
                           # This can be used to limit the amount of data
                           # per call. Use this for example to make your
                           # GUI more responsive 
                           # If set to 0, no limit is used (full update)                      
string[] delete_ids
---
# snapshots
ed_sensor_integration/ImageBinary[] images      # images
string[]                            image_ids   # image ids
time[]                              image_timestamps

# Ids of objects that were fitted
string[] entity_ids

uint32 new_revision
